# Generated by Django 4.1 on 2023-10-26 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biospecimen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, verbose_name='Название образца')),
                ('test_field', models.CharField(default='', max_length=250, verbose_name='Тестовое поле')),
                ('date', models.DateTimeField(verbose_name='Дата получения')),
            ],
            options={
                'verbose_name': 'Биологический образец',
                'verbose_name_plural': 'Биологические образцы',
            },
        ),
    ]
