# Generated by Django 4.1 on 2023-10-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biobank', '0002_biospecimen_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='biospecimen',
            name='file_name',
            field=models.CharField(default='', max_length=50, verbose_name='Название файла'),
            preserve_default=False,
        ),
    ]
