# Generated by Django 4.1 on 2023-10-31 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biobank', '0005_samplelocation_count_col_samplelocation_count_rows_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biospecimen',
            name='location',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='biobank.samplelocation'),
        ),
    ]
