# Generated by Django 4.1 on 2023-11-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biobank', '0010_alter_samplelocation_sample_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplelocation',
            name='sample_id',
            field=models.IntegerField(default=-1),
        ),
    ]
